"""ArtiFinder discovered-artifact schema.

Generated by ``generate_artifinder.py`` → ``artifinder.json``.

ArtiFinder (https://github.com/DistriNet/ArtiFinder) scrapes conference papers
directly and identifies links to their artifacts. The data lives in
https://github.com/DistriNet/ArtiFinder-Data. Unlike artifact-evaluation (AE)
results, ArtiFinder entries carry **no badges** and are **not manually
verified**, so they never contribute to any artifact / reproducibility score.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

CATEGORY = Literal["systems", "security"]


class ArtiFinderEntry(BaseModel):
    """A single artifact link discovered by ArtiFinder for a conference paper."""

    conference: str = Field(
        description="Conference abbreviation the paper belongs to, e.g. 'NDSS', 'USENIXSEC', 'SP', 'CCS'.",
        examples=["USENIXSEC"],
    )
    category: CATEGORY = Field(
        description="Research domain: 'systems' or 'security'. All current ArtiFinder venues are security.",
    )
    year: int = Field(
        ge=1990,
        le=2035,
        description="Publication year of the conference edition.",
        examples=[2024],
    )
    title: str = Field(
        description="Full paper title as recorded by ArtiFinder (DBLP-style, may include trailing period).",
        examples=["Framing Frames: Bypassing Wi-Fi Encryption by Manipulating Transmit Queues"],
    )
    authors: list[str] = Field(
        default_factory=list,
        description="Author names in DBLP form (disambiguation suffixes such as ' 0008' may be present).",
        examples=[["Domien Schepers", "Aanjhan Ranganathan", "Mathy Vanhoef"]],
    )
    page_link: str | None = Field(
        default=None,
        description="Link to the paper's landing page (DOI or proceedings URL) as recorded by ArtiFinder.",
        examples=["https://www.usenix.org/conference/usenixsecurity23/presentation/schepers"],
    )
    artifact_url: str = Field(
        description="The artifact URL discovered by ArtiFinder (normalised to include an https:// scheme).",
        examples=["https://github.com/domienschepers/wifi-framing"],
    )
    source: Literal["artifinder"] = Field(
        default="artifinder",
        description="Provenance marker. Always 'artifinder' for entries in this file.",
    )
    matched_ae: bool = Field(
        default=False,
        description=(
            "True when this ArtiFinder entry was matched (by title + author list) to a paper that also went "
            "through artifact evaluation and is present in artifacts.json."
        ),
    )
    paper_id: int | None = Field(
        default=None,
        ge=1,
        description="Stable integer ID of the matched paper in papers.json. Null when no AE match was found.",
        examples=[42],
    )

    model_config = {"extra": "forbid"}


class ArtiFinderCollection(BaseModel):
    """Collection of ArtiFinder-discovered artifact links."""

    root: list[ArtiFinderEntry]

    @classmethod
    def json_schema(cls) -> dict:
        return ArtiFinderEntry.model_json_schema()
